import { useFinanceStore } from '@/store/useFinanceStore'
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/Card'
import { Sparkles, AlertTriangle, CheckCircle } from 'lucide-react'

export default function Insights() {
  const insights = useFinanceStore(state => state.insights)

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Smart Insights</h1>
        <p className="text-muted-foreground mt-1">AI-powered behavioral analysis and personalized recommendations.</p>
      </div>
      
      <div className="grid gap-6">
        {insights.map((insight) => (
          <Card key={insight.id} className="glass">
            <CardHeader className="pb-3 border-b border-white/5">
              <div className="flex items-center space-x-3">
                <div className={`p-2 rounded-xl ${
                  insight.type === 'warning' ? 'bg-destructive/20 text-destructive' :
                  insight.type === 'success' ? 'bg-success/20 text-success' :
                  'bg-primary/20 text-primary'
                }`}>
                  {insight.type === 'warning' ? <AlertTriangle size={24} /> :
                   insight.type === 'success' ? <CheckCircle size={24} /> :
                   <Sparkles size={24} />}
                </div>
                <div>
                   <CardTitle className="text-lg">
                      {insight.type === 'warning' ? 'Spending Alert' :
                       insight.type === 'success' ? 'Goal Achievement' :
                       'Prediction Notice'}
                   </CardTitle>
                   <CardDescription className="text-xs mt-1 uppercase tracking-wider font-semibold opacity-70">
                     Generated by FinFlowy AI
                   </CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="pt-6">
              <p className="text-foreground leading-relaxed text-lg">
                {insight.message}
              </p>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  )
}
